version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  api:
    build: ./api
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3333 -b '0.0.0.0'"
    volumes:
      - .:/api/app
    ports:
      - "3333:3333"
    depends_on:
      - db

  client:
    build: ./client
    volumes:
      - ./client:/usr/src/app
      - ./client/node_modules:/usr/src/app/node_modules
    ports:
      - '3334:3000'
    environment:
      - NODE_ENV=development
    depends_on:
      - api
